bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/test.config
    - conf/test_full.config
    - assets/multiqc_config.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/nf-test.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/download_pipeline.yml
    - .github/workflows/fix-linting.yml
    - .github/workflows/release-announcements.yml
    - .github/workflows/template_version_comment.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/actions/
    - assets/nf-core-sp_segment_logo_light.png
    - docs/images/nf-core-sp_segment_logo_light.png
    - docs/images/nf-core-sp_segment_logo_dark.png
    - tests/default.nf.test
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - assets/email_template.html
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - docs/README.md
    - .prettierignore
    - .prettierrc.yml
  schema_params: false
  multiqc_config: false
  nextflow_config: false
nf_core_version: 3.3.2
org_path: null
repository_type: pipeline
template:
  author: WEHI SODA Hub
  description: Cell segmentation and downstream analysis pipeline for the COMET and MIBI spatial platforms
  force: true
  is_nfcore: true
  name: spatialproteomics
  org: nf-core
  outdir: spatialproteomics
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 0.1.0
update: null
