# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - python =3.10
  - tifffile
  - scikit-image
  - scikit-learn
  - scipy
  - pyyaml
  - matplotlib-base
  - numpy
  - tqdm
  - dask
  - dask-image
  - zarr >2
  - pip
  - git
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.10.0+cu128
      - torchvision
      - git+https://github.com/facebookresearch/segment-anything.git
      - git+https://github.com/vanvalenlab/cellSAM.git
