---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.11
  - tifffile =2025.6.11
  - numpy =1.26.4
  - scipy =1.14.1
  - scikit-image =0.24.0
  - shapely =2.0.6
